### ISSUE TITLE
merge overwriting database.yml

### ISSUE THREAD

**Issue by Turelyo** [andhapp/activerecord_sans_rails#1]
`ActiverecordSansRails::DB_CONFIG_ADMIN = ActiverecordSansRails::DB_CONFIG.merge({'database' => 'postgres', 'schema_search_path' => 'public'})`

This line forces the database name to be `postgres`, even if your database.yml specifies something else.

Discovered this in a new project for a microservice.  Added a few `puts` to my local installation to verify.

**Comment by andhapp** [comment]
Hey, found a better gem that solves the same problem, [standalone_migrations](https://github.com/thuss/standalone-migrations), therefore, closing this issue.

Thanks.
